import type { Metadata } from "next";
import Link from "next/link";
import { Orbitron, JetBrains_Mono, } from "next/font/google";
import "./globals.css";

const geistSans = Orbitron({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = JetBrains_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TekNest",
  description: "Generated by Xpektra",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden` }
      >
        <header className="p-4 w-full flex justify-between items-center">
          <h3>Logo</h3>
          <ul className="flex gap-2 items-center">
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/about">About</Link>
            </li>
            <li>
              <Link href="/contact">Contact</Link>
            </li>
          </ul>
        </header>
        <div className="grid grid-cols-5 h-80vh">
          <aside className="col-span-1 bg-gray-800">
            <p>Technology</p>
            <p>Design</p>
            <p>Business</p>
          </aside>
          <main className="col-span-4">
            {children}
          </main>
        </div>
        <footer className="flex 10-vh flex-col justify-center items-center p-2">
          &copy; 2025   Allrights reserved
        </footer>
      </body>
    </html>
  );
}
