import type { Metadata } from "next";
import { JetBrains_Mono, Mozilla_Text } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const geistMono = Mozilla_Text({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Xpektra",
  description: "Generated by Xpektra",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.variable} ${geistMono.variable} text-muted-foreground dark px-8 antialiased overflow-x-hidden max-w-[720px] mx-auto my-8 md:mt-16`}
      >

        <Header />

        {children}

      </body>
    </html>
  );
}
