import type { Metadata } from "next";
import { JetBrains_Mono, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Xpektra",
  description: "Generated by Xpektra",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.variable} ${geistMono.variable} text-muted-foreground dark px-8 antialiased overflow-x-hidden max-w-[720px] mx-auto my-8 md:mt-16`}
      >
        <header className="w-full flex justify-between items-center mb-8">
          <h3 className="text-foreground">X7</h3>
          <div className="">
            <Button variant="link" size="sm" asChild>
              <Link href="/projects">
                Projects
              </Link>
            </Button>
            <Button variant="link" size="sm" asChild>
              <Link href="/blogs">
                Blogs
              </Link>
            </Button>
          </div>
        </header>

        {children}

      </body>
    </html>
  );
}
